# Generated by Django 5.2 on 2025-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foodsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsource',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodsource',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
