# Generated by Django 5.2 on 2025-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
