# Generated by Django 5.2 on 2025-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsource',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
