# Generated by Django 5.2 on 2025-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_task_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsource',
            name='show_on_map',
            field=models.BooleanField(default=True),
        ),
    ]
